function sendCoppelia(sim,  clientID, pos, ori, velocity)
    [~, ~, ~, ~] = sim.simxCallScriptFunction(clientID,'base_visual', ...
                    sim.sim_scripttype_childscript,'setDroguiPosition', ...
                    [],[pos,ori],[],[],sim.simx_opmode_blocking);
    
    [~, ~, ~, ~] = sim.simxCallScriptFunction(clientID,'base_visual', ...
        sim.sim_scripttype_childscript,'setPropellersVelocity', ...
        [],velocity,[],[],sim.simx_opmode_blocking);
end

